### PR TITLE
excise2

### PR DESCRIPTION
**Pull request by AliRezaHassanloo2731**
i did my homework: favorite-food , second-favorite-food, last-3-countries .

### CODE REVIEW

**Comment by naresh699** [comment]
perfect. you can merge request

**Comment by AliRezaHassanloo2731** [comment]
I mereged week-1 with main branch

**Comment by jason-vasilev** [comment]
Well done following all the steps. Only thing I could note is that the files have had to be commited separately. Now it looks like step 6, 7, and 8 are done in one commit. You are welcome to try making a new branch, where you change the files again and commit them separately.

**Comment by AliRezaHassanloo2731** [comment]
Tanks alot, you are right

**Comment by jason-vasilev** [comment]
@AliRezaHassanloo2731  could you actually open a new branch from `main` and repeat the exercise (call the files in a different way) and try to commit them separately? It will be a good practice for what's called "cherry-picking" files to a commit.

**Pull request merged**
